[package]
name = "sudoku_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "main"
path = "src/main.rs"


[[bin]]
name = "basic_rule2"
path = "src/basic_rule2.rs"
